### ISSUE TITLE
osiris token grabber doesnt work

### ISSUE THREAD

**Issue by T1Founder** [the-cult-of-integral/discord-raidkit#110]
osiris token grabber gives incorrect token when I tested on myself. please fix

**Comment by the-cult-of-integral** [comment]
After testing on myself, I pushed a fix for this a few days ago, and it worked fine. What version of Discord Raidkit are you using?

If you're using v2.4.5, and it still isn't working, could you provide the character length of your actual token and the character length of the token that the grabber gave?

**Comment by T1Founder** [comment]
Hi yes. I am using v2.4.5, and it isn't working for me..
Here is the character length of grabbed token : 177
Here is the character length of actual token: 72

not sure why this is happening..

**Comment by the-cult-of-integral** [comment]
My Discord is XORBit64 - Could you add me so communication is quicker?

**Comment by GhostYT23** [comment]
I did 2 test whit two diffenet accounts , in the first one the token missed 2 charaters at the start (lenght of the token pulled : 70 ; actual lenght : 72 ) , and the second one was perfect.

Just to give you more contex in both cases the token was pulled by Brave.

**Comment by the-cult-of-integral** [comment]
I just released v2.5.0, but with no changes to the grabber. I will do some more investigation for release v2.5.1. Discord could have updated its tokens so that they no longer always match whatever regex the token grabber is currently using.

After playing around with v2.4.4 for myself, I found no tokens for the local application Discord, but I found a token in my Chrome browser. So, as I said, Discord has changed something, I think. Again, I'll do some more investigating to see whether I can get a working grabber that works for everything again by v2.5.1's release.

@GhostYT23  @T1Founder

**Comment by GhostYT23** [comment]
> I just released v2.5.0, but with no changes to the grabber. I will do some more investigation for release v2.5.1. Discord could have updated its tokens so that they no longer always match whatever regex the token grabber is currently using.
> 
> After playing around with v2.4.4 for myself, I found no tokens for the local application Discord, but I found a token in my Chrome browser. So, as I said, Discord has changed something, I think. Again, I'll do some more investigating to see whether I can get a working grabber that works for everything again by v2.5.1's release.
> 
> @GhostYT23 @T1Founder

I don’t know if they changed it again but the release before 2.5.0 was working fine to me last time I used it it was couple weeks ago tho

**Comment by the-cult-of-integral** [comment]
I am closing this issue and moving it to [Issue 139](https://github.com/the-cult-of-integral/discord-raidkit/issues/139) since it concerns the most up-to-date version of the raidkit.

@T1Founder
