### ISSUE TITLE
Unable to Download .exe file

### ISSUE THREAD

**Issue by iron-coder12** [the-cult-of-integral/discord-raidkit#78]
Every time i try to download the file my browser doesn't let me and says Failed - Virus Detected

**Comment by the-cult-of-integral** [comment]
Unfortunately, things like this do tend to happen with repositories such as mine. It is undoubtedly due to the browser recognising Osiris' token-grabbing abilities.

I'm not sure what browser you're using, but if you're using Chrome, you can go to the security section of Chrome settings and disable protection for downloads (I'm sure similar settings exist for other browsers). You may also want to add the downloads folder to Windows Defender's exclusions, temporarily, whilst you set up a proper place to store the Discord Raidkit that is permanently excluded from malware scans. 

Remember, if you do set up a folder to be permanently excluded from Window's anti-malware (or any other anti-malware), make sure that only files you trust enter it! Be internet safe.

Apologies for any inconvenience, @iron-coder12

**Comment by iron-coder12** [comment]
upon running the program Osiris it prompts for a discord authentication token. What am i meant to put in there

**Comment by iron-coder12** [comment]
Also does it have a documentation or something?
