### ISSUE TITLE
what are u doin download!!!

### ISSUE THREAD

**Issue by Nitrotype338** [the-cult-of-integral/discord-raidkit#94]
everytime i try to download the file it will say its a dangerous file and will delete it. i know it says to make a folder and put it in there and add it to the protector but it will just delete the file and i will have no time to even do it. what should i do?

**Comment by Nitrotype338** [comment]
and also it says there is a trojan detected

**Comment by Justman100** [comment]
@the-cult-of-integral

**Comment by the-cult-of-integral** [comment]
If you're using Windows Defender, you could add a folder to its exclusions, then download directly to that folder rather than downloads.

If you're using some external anti-malware that is reporting the software, just use Windows Defender and get rid of the other shit; defender is more than enough in 2024 if paired with common sense.

The trojan detected is likely due to Osiris' containing code to modify registries of its targets so it can token grab on each logon. Note that this affects the target, not you.

@Nitrotype338

**Comment by Codeman04TheFreaking2nd** [comment]
Lol but u had the audacity to let it so called "access the internet" I saw a fucking webhook in the exe

**Comment by Justman100** [comment]
> Lol but u had the audacity to let it so called "access the internet" I saw a fucking webhook in the exe

A webhook?
